import {
  LayoutDashboard,
  Users,
  Database,
  Stamp,
  ScrollText,
  ClipboardCheck,
  UsersRound,
  History,
  BadgeCheck,
  Wallet,
  FileBarChart,
  ShieldCheck,
  PiggyBank,
  Receipt,
  ListChecks,
  Calculator,
  GitBranch,
  Coins,
  FilePlus2,
  Banknote,
  ShoppingCart,
  Boxes,
  Truck,
  Store,
  Gem,
  Gift,
  Clock,
  ShoppingBag,
  type LucideIcon,
} from "lucide-react";
import type { Role } from "@/lib/casheva-data";

export type NavItem = {
  title: string;
  url: string;
  icon: LucideIcon;
  badge?: string;
};

export const roleNav: Record<Role, NavItem[]> = {
  "Admin Koperasi": [
    { title: "Dashboard", url: "/", icon: LayoutDashboard },
    { title: "Manajemen User", url: "/users", icon: Users },
    { title: "Data Anggota", url: "/anggota", icon: UsersRound },
    { title: "Pengajuan Pinjaman", url: "/pengajuan", icon: FilePlus2 },
    { title: "Simpanan Anggota", url: "/simpanan", icon: PiggyBank },
    { title: "Pencairan & Invoice", url: "/pencairan", icon: Receipt },
    { title: "Rekap Angsuran", url: "/angsuran", icon: ListChecks },
    { title: "Kasir POS Toko", url: "/pos", icon: ShoppingCart },
    { title: "Katalog & Stok Barang", url: "/inventori", icon: Boxes },
    { title: "Supplier & Pengadaan", url: "/supplier", icon: Truck },
    { title: "Pesanan Antar & Piket", url: "/pesanan-antar", icon: Clock },
    { title: "Marketplace Anggota", url: "/marketplace-anggota", icon: Store },
    { title: "Unit Gadai & Lelang", url: "/gadai", icon: Gem },
    { title: "Poin & Undian RAT", url: "/poin-undian", icon: Gift },
    { title: "Riwayat Transaksi Toko", url: "/toko-transaksi", icon: ShoppingBag },
    { title: "Laporan Keuangan Toko", url: "/laporan-toko", icon: FileBarChart },
    { title: "Antrean Verifikasi (Jurbay)", url: "/verifikasi", icon: ShieldCheck },
    { title: "Antrean Rekomendasi (Dan/Ka)", url: "/rekomendasi", icon: ClipboardCheck },
    { title: "Persetujuan ACC (Keprim)", url: "/acc", icon: BadgeCheck },
    { title: "Likuiditas Kas", url: "/likuiditas", icon: Wallet },
    { title: "Pengawasan SHU", url: "/shu", icon: Calculator },
    { title: "Laporan Keuangan", url: "/laporan", icon: FileBarChart },
    { title: "Master Data TNI AD", url: "/master-data", icon: Database },
    { title: "Kopstuk & TTD", url: "/kopstuk", icon: Stamp },
    { title: "Audit Logs", url: "/audit", icon: ScrollText },
    { title: "Audit Flow Approval", url: "/audit-flow", icon: GitBranch },
  ],
  "Kasir Toko": [
    { title: "Dashboard", url: "/", icon: LayoutDashboard },
    { title: "Kasir POS Toko", url: "/pos", icon: ShoppingCart },
    { title: "Katalog & Stok Barang", url: "/inventori", icon: Boxes },
    { title: "Pesanan Antar & Piket", url: "/pesanan-antar", icon: Clock },
    { title: "Riwayat Transaksi Toko", url: "/toko-transaksi", icon: ShoppingBag },
    { title: "Poin & Undian RAT", url: "/poin-undian", icon: Gift },
    { title: "Unit Gadai & Lelang", url: "/gadai", icon: Gem },
    { title: "Laporan Keuangan Toko", url: "/laporan-toko", icon: FileBarChart },
  ],
  "Pimpinan / Dan / Ka": [
    { title: "Dashboard", url: "/", icon: LayoutDashboard },
    { title: "Antrean Rekomendasi", url: "/rekomendasi", icon: ClipboardCheck },
    { title: "Data Anggota Satuan", url: "/anggota", icon: UsersRound },
    { title: "Riwayat Pinjaman Satuan", url: "/pinjaman", icon: History },
    { title: "Katalog Belanja Toko", url: "/katalog-belanja", icon: ShoppingBag },
  ],
  Keprim: [
    { title: "Dashboard", url: "/", icon: LayoutDashboard },
    { title: "Antrean Rekomendasi", url: "/rekomendasi", icon: ClipboardCheck },
    { title: "Persetujuan Akhir (ACC)", url: "/acc", icon: BadgeCheck },
    { title: "Likuiditas Kas", url: "/likuiditas", icon: Wallet },
    { title: "Laporan Keuangan Toko", url: "/laporan-toko", icon: ShoppingBag },
    { title: "Laporan Keuangan", url: "/laporan", icon: FileBarChart },
  ],
  Bendahara: [
    { title: "Dashboard", url: "/", icon: LayoutDashboard },
    { title: "Pengajuan Pinjaman", url: "/pengajuan", icon: FilePlus2 },
    { title: "Antrean Rekomendasi", url: "/rekomendasi", icon: ClipboardCheck },
    { title: "Simpanan Anggota", url: "/simpanan", icon: PiggyBank },
    { title: "Pencairan & Invoice", url: "/pencairan", icon: Receipt },
    { title: "Rekap Angsuran", url: "/angsuran", icon: ListChecks },
    { title: "Kasir POS Toko", url: "/pos", icon: ShoppingCart },
    { title: "Katalog & Stok Barang", url: "/inventori", icon: Boxes },
    { title: "Supplier & Pengadaan", url: "/supplier", icon: Truck },
    { title: "Laporan Keuangan Toko", url: "/laporan-toko", icon: FileBarChart },
  ],
  "Juru Bayar": [
    { title: "Dashboard", url: "/", icon: LayoutDashboard },
    { title: "Antrean Verifikasi", url: "/verifikasi", icon: ShieldCheck },
    { title: "Pencairan & Invoice", url: "/pencairan", icon: Receipt },
    { title: "Rekap Angsuran", url: "/angsuran", icon: ListChecks },
  ],
  Anggota: [
    { title: "Dashboard", url: "/", icon: LayoutDashboard },
    { title: "Katalog Belanja Toko", url: "/katalog-belanja", icon: ShoppingBag },
    { title: "Pesanan Saya & Piket", url: "/pesanan-antar", icon: Clock },
    { title: "Poin & Undian RAT", url: "/poin-undian", icon: Gift },
    { title: "Marketplace UMKM", url: "/marketplace-anggota", icon: Store },
    { title: "Layanan Gadai & Lelang", url: "/gadai", icon: Gem },
    { title: "Rincian Gaji & Potongan", url: "/gaji", icon: Banknote },
    { title: "Pengajuan USIPA", url: "/pengajuan", icon: FilePlus2 },
    { title: "Simpanan Saya", url: "/simpanan", icon: PiggyBank },
    { title: "Riwayat Angsuran", url: "/angsuran", icon: ListChecks },
  ],
  "Pengawas Koperasi": [
    { title: "Dashboard", url: "/", icon: LayoutDashboard },
    { title: "Pengawasan SHU", url: "/shu", icon: Calculator },
    { title: "Laporan Keuangan Toko", url: "/laporan-toko", icon: ShoppingBag },
    { title: "Laporan Pendapatan & Biaya", url: "/laporan", icon: Coins },
    { title: "Audit Flow Approval", url: "/audit-flow", icon: GitBranch },
  ],
};

